CREATE ROLE confort_user WITH LOGIN PASSWORD 'confort_pass';
GRANT SELECT,UPDATE,INSERT,DELETE ON ALL TABLES IN SCHEMA public TO confort_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO confort_user;